name: "Docker"
on:
  push:
    branches:
      - 'main'
  workflow_call:
#    inputs:
#      image_name:
#        required: true
#        type: string
#      tag:
#        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Set the tag
#        run: |
#          if [ -z "${{inputs.tag}}" ]
#          then
#            echo "final_tag=latest" >> $GITHUB_ENV
#          else
#            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
#          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: elstepanyan/flask_app:latest
          context: .
#          push: true
#          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{inputs.image_name}}:${{env.final_tag}}